### ISSUE TITLE
Task 12 (generic modal)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#9]
We want to make a minimalist version of bootstrap modals. Note that bootstrap modal consists of there nested blocks:
- `.modal` class: which is a `position:fixed`  wrapper for the modal which covers the whole page and creates a scrolling content for the modal
- `modal-dialogue`: this wrapper is mainly used for vertical alignment of the modal content
- `modal-content`: the wrapper for the content

In out design the first two blocks will be created by javascript and the styles will be hard coded in the style. You just need to design the classes for content that produce different type of animations. 

The html boilerplate for a modal will be like

```html
<!-- content wrapper: feel free to add more styles if need be (maybe add display:flex for better alignment?), but i guess these are enough. No need to make these styles into css class. They will be generated by the javascript modal controller -->
<div style="position:fixed; width:100%; height:100%; top:0; left:0; z-index:10; display:none">   

  

    <!-- this is the modal content element which you have to write style for -->
     <article class="s-modal">
         <!-- any content here, you may use Lorem text to fill it up ... -->
     </article>

  

</div>
```

To show/hide the modal all we need to do is to change the `display` style of the content wrapper. For your design purpose you can just set it to `block` so that the modal always shows.

Adding styles to the `<article>` tag
------------------------------------------------------------
`<article>` represent the main part of our modal and can contain anything. Generally speaking it needs no special style other than limiting its width by `width:500px` and may be align it horizontally by `margin:0 auto` ... Now we want to have some animation when modal is open/close. To do so, the javscript part will add some *directive classes* to the article as follows:

- `opening`: when the modal is opening. This style is supposed to create an opening animation for the modal content (namely the `<article>` element - note that the context wrapper is assumed to be visible). After the animation is done the javascript will remove this class
-  `closing`: when the modal is closing. This style is supposed to create a closing animation for the modal content (namely the `<article>` element - note that the context wrapper is assumed to be visible). After the animation is done the javascript will remove this class

Now you need to design a class called `s-modal` to be applied to the `<article>` modal. This class itself adds some basic layout feature to the modal window such as white background, padding, etc. In addition to that it is supposed to create different openning/closing animations as well. To specify the animation type we use modifier classes. For example the combination `s-modal s-modal--slide-left` creates a slide left animation on opening and its reverse animation (=slide right) on closing.  (The bare class `s-modal` creates no animation by itself). So in summary here are the styles for different combinations:

- `s-modal` -> basic styles for the modal window: white background, padding, shadow, etc.
- `s-modal s-modal--slide-left` -> creating a slide left animation on opening (= `s-modal s-modal--slide-left opening`) and a slide right animation on closing  (= `s-modal s-modal--slide-left closing`)
- `s-modal s-modal--slide-right` (similar to slide-left but right slides)
- `s-modal s-modal--slide-below` (similar to slide-left but slides from below) 
- `s-modal s-modal--center-y` -> vertically centers the modal
- width sizes (based on bootstrap breakpoints) `s-modal--sm`, `s-modal--md`, ... `s-modal--xxl`, and also add `s-modal--fs` for full screen size

Create an html file to show case these different modal types. For some of the show-cases make the modal long enough so that we need to scroll, this way we test the scrolling modal as well (you may need to apply scroll lock style to the body to make the modal scrolling work. See the class modal-open of bootstrap. Feel free to add this style to the body if it's needed).

**Comment by pmvald** [comment]
@YusukeYoshihiro Please move to this task instead of task 23. This task is more general and it includes the stuff in task 23 as well. Once you do this we can close task 23 as well. Thanks.

**Comment by YusukeYoshihiro** [comment]
Hi, Peter. I'm sorry for the late to submit, but I did update task 12.
Please confirm it and give me some advice.

①`•.modal class: which is a position:fixed wrapper for the modal which covers the whole page and creates a scrolling content for the modal`
-> I did and it is possible to scroll while modal open and prevent scroll for the body by using `  height: 100vh;
        overflow: hidden; position: fixed;` on body tags, and `overflow-y: auto; -webkit-overflow-y: auto; height: 80vh;` for `s-modal` class to scroll.
```css
      body.s-modal--open {
        height: 100vh;
        overflow: hidden;
        position: fixed;
      }
      .s-modal {
        background-color: white;
        border: 2px solid red;
        border-radius: 15px;
        width: 500px;
        margin: 2rem auto;
        align-self: center;
        transition: all 1s ease-in;
        display: none;
        padding: 15px;
        overflow-y: auto;
        -webkit-overflow-y: auto;
        height: 80vh;
      }
```
②`•modal-dialogue: this wrapper is mainly used for vertical alignment of the modal content.`
`•modal-content: the wrapper for the content.`
-> I did follow your structure and nested and wrapped blocks.

```html
   <article class="s-modal" id="s-modal">
        <div class="s-modal__dialogue">
          <div class="s-modal__content">
            <div class="s-modal__content--header">
              <h4>Modal</h4>
              <button class="s-modal__content--closebtn" onclick="closeModal()">
                <span>&times;</span>
              </button>
            </div>
                            •
                            •
```

③`In out design the first two blocks will be created by javascript and the styles will be hard coded in the style. You just need to design the classes for content that produce different type of animations.`
-> In this task, as you mentioned, I wrote css and javaScript code as hard code so, not to use scss, so if you need to modified css head code part as scss file, please let me know and also give me some advice to write shortly like use @mixin  because I used same properties repeatedly on the animation part like below.

 ```css
       .s-modal--slide-left.opening {
        -webkit-animation: slide-left-ani 1s ease-in-out;
        animation: slide-left-ani 1s ease-in-out;
      }

      .s-modal--slide-left.closing {
        -webkit-animation: slide-close-left-ani 1s ease-in-out;
        animation: slide-close-left-ani 1s ease-in-out;
      }

      .s-modal--slide-right.opening {
        -webkit-animation: slide-right-ani 1s ease-in-out;
        animation: slide-right-ani 1s ease-in-out;
      }

      .s-modal--slide-right.closing {
        -webkit-animation: slide-close-right-ani 1s ease-in-out;
        animation: slide-close-right-ani 1s ease-in-out;
      }
```
③`<article> represent the main part of our modal and can contain anything. Generally speaking it needs no special style other than limiting its width by width:500px and may be align it horizontally by margin:0 auto ... Now we want to have some animation when modal is open/close. To do so, the javscript part will add some directive classes to the article as follows:`
-> I did, and put `width:500px` on `<article>` class, and I adopted ` margin: 2rem auto;` to style as horizontally and to have gap from top. And wote JavaScript part as hard code too, and added classed as directly.
```css
 .s-modal {
        background-color: white;
        border: 2px solid red;
        border-radius: 15px;
        width: 500px;
        margin: 2rem auto;
```
`④•opening: when the modal is opening. This style is supposed to create an opening animation for the modal content (namely the <article> element, note that the context wrapper is assumed to be visible). After the animation is done the javascript will remove this class.`
`•closing: when the modal is closing. This style is supposed to create a closing animation for the modal content (namely the <article> element - note that the context wrapper is assumed to be visible). After the animation is done the javascript will remove this class.`
-> I did, please confirm it.
```html
<script>
      const modal = document.getElementById("s-modal");
      function openModal(direction) {
        // code here
        modal.classList.add("opening");
        document.body.classList.add("s-modal--open")
        if (direction === "left") {
          modal.classList.add("s-modal--slide-left");
        } else if (direction === "right") {
          modal.classList.add("s-modal--slide-right");
        } else if (direction === "below") {
          modal.classList.add("s-modal--slide-below");
        } else if (direction === "vertical") {
          modal.classList.add("s-modal--slide-vertical");
        }
      }

      function closeModal(direction) {
        // code here
        modal.classList.add("closing");
        modal.classList.remove("opening");
        document.body.classList.remove("s-modal--open")
        setTimeout(function () {
          modal.classList.remove(
            "s-modal--slide-left",
            "s-modal--slide-right",
            "s-modal--slide-below",
            "s-modal--slide-vertical"
          );
          modal.classList.remove("closing");
        }, 800);
      }
    </script>
```
⑤`s-modal -> basic styles for the modal window: white background, padding, shadow, etc.`
`s-modal s-modal--slide-left -> creating a slide left animation on opening (= s-modal s-modal--slide-left opening) and a slide right animation on closing (= s-modal s-modal--slide-left closing)`
`s-modal s-modal--slide-right (similar to slide-left but right slides)`
`s-modal s-modal--slide-below (similar to slide-left but slides from below)`
-> I did.
`s-modal s-modal--center-y -> vertically centers the modal
width sizes (based on bootstrap breakpoints) s-modal--sm, s-modal--md, ... s-modal--xxl, and also add s-modal--fs for full screen size`
-> _I couldn't made it just this part of  `s-modal--sm, s-modal--md, ... s-modal--xxl, and also add s-modal--fs` for full screen size, so please give me suggestions and lectures._

Thanks.
